/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class advprogclasses_JniSum */

#ifndef _Included_advprogclasses_JniSum
#define _Included_advprogclasses_JniSum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     advprogclasses_JniSum
 * Method:    calculateSum
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_advprogclasses_JniSum_calculateSum
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
